### ISSUE TITLE
[IMP] Imágenes por defecto para los petusers

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#11]
Una imagen por defecto diferente según el tipo de servicio

**Comment by hielfx** [comment]
Se propone como mejora de la versión actual

**Comment by danmarrod** [comment]
Esta incidencia es la más antigua y nadie la ha pillado. Es importante porque cuando hacemos las diferentes búsquedas en las demos siempre sale la misma imagen de la chica con el perro, sea company, sitter o manolito.

**Comment by PedroGalvan** [comment]
He hecho que, al buscar desde index, se muestre una para Sitters, otra para Shippers y otra para company.

Con eso vale?

Si es así, cierra la issue! =P

**Comment by PedroGalvan** [comment]
![captura1](https://cloud.githubusercontent.com/assets/15108206/15193248/24d112fe-17bd-11e6-8b61-56660b67bf43.PNG)
![captura2](https://cloud.githubusercontent.com/assets/15108206/15193251/270144cc-17bd-11e6-848d-5819fff1a551.PNG)
![captura3](https://cloud.githubusercontent.com/assets/15108206/15193252/29263d48-17bd-11e6-8121-604dd8a60e15.PNG)

**Comment by danmarrod** [comment]
De pm, era eso. Gracias.
