### ISSUE TITLE
Imagen de registro en Index para PetShipper y Company

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#13]
Añadir imagenes directas para el registro de PetShipper y Company en el Index, igual que están PetSitter y PetOwner

**Comment by valbarsau** [comment]
¿Exactamente a que se refiere?

**Comment by danmarrod** [comment]
Lo que comentó ayer Pedro, añadir una imagen como las de esta foto para loss otros usuarios

![imagen](https://cloud.githubusercontent.com/assets/15341290/14860383/e5dd8aec-0ca8-11e6-8c23-777414a1ceca.png)

**Comment by valbarsau** [comment]
Eso ya esta arreglado, alguien lo arregló.

![image](https://cloud.githubusercontent.com/assets/15670602/14860442/24148220-0ca9-11e6-8ebc-80d8352dc5f5.png)

**Comment by danmarrod** [comment]
Vale perfect, tuvo que ser Pedro anoche. No lo tengo actualizado. Cierro la incidencia.
