### ISSUE TITLE
ERROR: Varios errores en welcome index

### ISSUE THREAD

**Issue by hielfx** [ISPP/pet-care#2]
- Cuando entras en la pagina principal y le das a _Service type_ no se ven porque están con el texto blanco ([imagen 1](https://gyazo.com/23a4dcdda3924cba676de4d1597c520f))
- Cuando te logeas y te redirecciona al index no aparece nada para poder buscar ([imagen 2](https://gyazo.com/fb76c2ad73be342f64bdd9bcfe148d1d))

**Comment by viccanjua** [comment]
La había solucionado ayer. Logueado como petShipper o company no tiene que salir el buscador, no tiene sentido.
