### ISSUE TITLE
Perfil company con vista sin formatear

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#25]
Como usuario Company, desde "My Profile" accedemos a una vista sin formatear.

**Comment by hielfx** [comment]
Mi commit no esta relacionado, me confundí de número de incidencia al hacer commit

**Comment by hielfx** [comment]
Esta incidencia se ha sulucionado. No se sabe quién la ha realizado. Adjunto captura y cierro ala incidencia: 
![b91593102abe072abdcf65e2b621da21](https://cloud.githubusercontent.com/assets/7794231/15029400/a540d822-124d-11e6-9e1a-3b384ad16b3e.png)
Considero que el diseño es bueno como para marcarla como solucionada.
