### ISSUE TITLE
Ver Comentarios, NullPointerException

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#26]
Desde el perfi de admin, al ver una Complaint que acabo de crear con un comentarios y que no está asignada, intento ver los comentarios y salta un "NullPointerException".

Añado pantallazo de la complaint.

![cap1](https://cloud.githubusercontent.com/assets/15341290/14963720/3dfd397a-10a5-11e6-8cf9-7fa8882d3e5d.png)

**Comment by moillagar** [comment]
ese botón no debe de aparecer ahí, ya que no tiene asignada esa complaint (no puede ver los comentarios de complaint). Yo e hecho complaint y lo e modelado así, si creéis conveniente que los pueda ver, solo hay que cambiar en el servicio

**Comment by danmarrod** [comment]
Creo que entonces tal como lo has modelado estaría bien, entonces habría que ocultar el botón. Dejo abierta la incidencia y cambiamos a ocultar el botón.

**Comment by valbarsau** [comment]
Me asigno yo la incidencia para arreglarlo. La solución pasaría por quitar el botón de listar comentarios de esa vista, no?

**Comment by valbarsau** [comment]
Soluciionado.
