### ISSUE TITLE
Cambiar botón Save por Search en búsqueda de Trips

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#28]
Como PetOwner, en Trip>Find Trips... , la búsqueda tiene un botón de Save que habría que cambiar por Buscar. Agrego pantallazo.
![cap1](https://cloud.githubusercontent.com/assets/15341290/14965262/b696130a-10ac-11e6-8659-7c02b1299201.png)

**Comment by hielfx** [comment]
En esta incidencia también está incluída la de la url (se muestra trip/petOwner//findTrips.do)

**Comment by hielfx** [comment]
¿Habria que cambiar el css del botón también?

**Comment by hielfx** [comment]
Cierro esta incidencia. Si se va a cambiar el css creamos otra incidencia o se reabre.
