### ISSUE TITLE
[IMP] Quitar * en precio por día

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#29]
En los resultados de la búsqueda, el precio por día de cada usuario lleva un asterisco que no queda muy bien y confunde. Con dejar la anotación "Los precios en blanco indican el dinero por día completo" creo es suficiente.

![cap](https://cloud.githubusercontent.com/assets/15341290/14983033/e85fd860-113a-11e6-9fe7-a0e671baeb43.png)

**Comment by valbarsau** [comment]
Me la asigno para quitarla.

**Comment by valbarsau** [comment]
![image](https://cloud.githubusercontent.com/assets/15670602/14996933/a3dab1a0-117c-11e6-8cb1-7605f4e577af.png)
Arreglado

**Comment by danmarrod** [comment]
Esto sigue apareciendo.

**Comment by PedroGalvan** [comment]
ups...

**Comment by PedroGalvan** [comment]
Eliminado de los resultados del buscador principal
![captura](https://cloud.githubusercontent.com/assets/15108206/15197484/f2a30a16-17d1-11e6-8e7d-33190f9e68d4.PNG)
