### ISSUE TITLE
ERROR: Acceder a una url sin estar autenticado muetra error de login

### ISSUE THREAD

**Issue by hielfx** [ISPP/pet-care#3]
Cuando se intenta acceder a una url sin estar autenticado y necesitas estarlo muetra directamente un error usuario y contraseña incorrecto ([imagen del error](https://gyazo.com/7f804b7f90e18cc7dd2fc1f355a3ab28))

Esto puede deberse a que el login esta en un popup, el cual no se muestra al acceder a las urls

**Comment by PedroGalvan** [comment]
https://github.com/ISPP/petcare/issues/10
