### ISSUE TITLE
Problema listar comentarios

### ISSUE THREAD

**Issue by moillagar** [ISPP/pet-care#30]
Cuando nos logueamos como administrador y listamos los comentarios de una complaint, aparece varios enlaces para crear commentarios, solo debe de aparecer uno en el ultimo lugar. Creo que si listas los comentarios desde cualquier otro rol, debe de ocurrir lo  #m
![problema](https://cloud.githubusercontent.com/assets/15704818/14996887/74c95d80-117c-11e6-804f-781535c22694.PNG)
ismo. Arreglar esto # #

**Comment by valbarsau** [comment]
De acuerdo, veré cuál es el problema.
Me la asigno.

**Comment by valbarsau** [comment]
Se ha añadido un controlador una variable que representa el id de la complaint con la que no sera necesario acceder al comment y podremos acceder fuera del forEach. Ya esta solucionado
