### ISSUE TITLE
Los suppliers se sobreescriben si tienen la misma dirección (Google maps)

### ISSUE THREAD

**Issue by hielfx** [ISPP/pet-care#33]
En el mapa de google, cuando hay varios suppliers que tienen exatamente las mismas coordenadas geográficas (extraídas de la dirección) solamente se guarda el infowindow del último que se ha añadido, perdiendo así los anteriores: En la [imagen](https://gyazo.com/b10b3008502206dc8ab1fcda032bc3c6) se ve que hay varios suppliers con la misma dirección y el infowindow es solamente del último.

**Comment by PedroGalvan** [comment]
La probabilidad de que dos personas pongan exactamente la misma dirección es muy remota.
Yo me preocuparía por indicar de alguna forma que el address que queremos debe ser de tipo: C/CallePrueba , Nº Prueba , Ciudad Prueba

**Comment by hielfx** [comment]
La marco en principio como WONTFIX y la cierro. Si sirge algo sobre lo que comentar al respecto la volvemos a abrir
