### ISSUE TITLE
Vista buscar  trip

### ISSUE THREAD

**Issue by moillagar** [ISPP/pet-care#41]
La vista es cáncer. Arreglar los botones, nos lo dijeron en el feedback y debemos de hacerlo

**Comment by danmarrod** [comment]
Feedback dado que hay que corregir:

- Las letras del primer nivel de la jerarquia estan bien, pero en los segundos el espaciado es mayor y se dilata la información.

- Hay botones negativos que son más llamativos, lo que incita a darle más a cancelar y borrar que otras acciones en la aplicación

- Cuidar la interfaz: botones con distintos colores, espaciados de letras, no texto en un 5% y resto en blanco.

**Comment by valbarsau** [comment]
Ok aprovecho y la arreglo. Me la asigno. Los botones los he cambiado pero el estilo no es el mas adecuado.

**Comment by valbarsau** [comment]
![image](https://cloud.githubusercontent.com/assets/15670602/15131609/bd2c34d8-1651-11e6-8029-cda6fa626e33.png)
Lo cierro.
