### ISSUE TITLE
[IMP] Google Maps, mejorar marcadores

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#42]
Incluir una imagen diferente para los marcadores que no sea el que viene por defecto y agrandarla lo posible para que en las demos se vean bien.

**Comment by hielfx** [comment]
Lo que se muestra es exactamente lo mismo que la lista, ya que se toma el contenido de los divs. Habria que tocar el listado para mostrarlo más grande o hacer zoom a la hora d hacer la demo

**Comment by danmarrod** [comment]
No me refería a las tarjetas de los petusers, sino al icono de google que marca el sitio
![google-11](https://cloud.githubusercontent.com/assets/15341290/15099284/84be32b4-1551-11e6-877e-5d1789b28a2b.jpg)

**Comment by hielfx** [comment]
que quieres que ponga?

**Comment by danmarrod** [comment]
Pues podriamos poner algún icono de esos graciosode animales, busco alguno.

**Comment by danmarrod** [comment]
Te paso algunos que he visto que podrían quedar bien, ponle el que tu veas que queda mejor.

![185232-consultorio-veterinario-alem-icono-02](https://cloud.githubusercontent.com/assets/15341290/15099403/bd62c50a-1554-11e6-8074-1b6b73f62914.png)
![icon2](https://cloud.githubusercontent.com/assets/15341290/15099404/bd67bb28-1554-11e6-81b6-64c39d98f2f4.png)
![pet-icon](https://cloud.githubusercontent.com/assets/15341290/15099405/bd6a7a8e-1554-11e6-9cff-50e87756f900.png)
![pet-icon2](https://cloud.githubusercontent.com/assets/15341290/15099406/bd6faa40-1554-11e6-87b7-7b0cd402ad14.png)

**Comment by danmarrod** [comment]
Añadimos los iconos para cada uno de los servicios:

![marker petcare 2a](https://cloud.githubusercontent.com/assets/15341290/15118432/72101b6c-160c-11e6-8d59-075993dc6c01.png)
![marker petcare 4a](https://cloud.githubusercontent.com/assets/15341290/15118433/72134e5e-160c-11e6-8e0a-b1c2d94c2997.png)
![marker petcare 7](https://cloud.githubusercontent.com/assets/15341290/15118434/7213500c-160c-11e6-9eaa-9d6e6d99f3f6.png)

**Comment by hielfx** [comment]
Doy por terminada esta incidencia. Si se cambia de opinion se reabre.
Al final queda como sigue:

- PetSitter:
![d94fb2165ca7df442e9cd71dd7ce67d3](https://cloud.githubusercontent.com/assets/7794231/15164938/7afd63a4-1712-11e6-9696-023a522002aa.png)

- PetShipper:
![e1c0df451ecef5f0c559319c29685b49](https://cloud.githubusercontent.com/assets/7794231/15164944/83e89f38-1712-11e6-9ea8-f19574023df6.png)

- Company:
![f60311d20991b587a9c2418064e58de4](https://cloud.githubusercontent.com/assets/7794231/15164945/87edf5ba-1712-11e6-8cbb-a00ee945824b.png)

**Comment by danmarrod** [comment]
De arte, crema crema.

**Comment by danmarrod** [comment]
Por favor invertir los iconos de sitter y company, creo que es más descriptivo la casa para los hoteles. Es mi opinión, si en general lo veis al revés comentarlo para dejarlo entonces tal cual.

**Comment by hielfx** [comment]
Ya esta hecho
