### ISSUE TITLE
[IMP] Mostrar ruta google maps al crear un trips

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#45]
Vista My Trip > igual que "CrearTrip",  que aparezca un mapa de google map con la ruta, la imagen de un coche. La cosa es adornarlo como sea

**Comment by hielfx** [comment]
Se ha solucionado esta incidencia. Quedaría así de momento:
![37e929a570fb1681a6d93ff09cc2656d](https://cloud.githubusercontent.com/assets/7794231/15166055/69d4e0f8-171b-11e6-99c8-7debea2101da.png)

@danmarrod Tu decides si la cerramos ya o mejoramos algo. De momento la dejo abierta

**Comment by danmarrod** [comment]
Perfe, viste mucho a la vista. Sólo un cambio, estaba pensando que saliera más pequeño, y en vez de abajo, mejor a su derecha, no sé si quedaría mejor. Además de que la barra de solapa la maldita.

**Comment by hielfx** [comment]
Ahora mismo lo he puesto así:
![3498cbd6a2e890c5997b2ad58523a198](https://cloud.githubusercontent.com/assets/7794231/15182077/ecfc0fc8-178a-11e6-9821-f49cec8d22fa.png)

**Comment by hielfx** [comment]
Se ha mejorado para que quede así:
![0942eac09c5f971dc1153e19821999b8](https://cloud.githubusercontent.com/assets/7794231/15195584/c7153850-17c8-11e6-8bc1-b171290c39ed.png)
