### ISSUE TITLE
Mejorar estilos de los botones

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#47]
Aquí hay algunos complementos para bootstrap, por si pueden valer. Icon Animator
http://www.psdahtmlpasoapaso.com/blog/complementos-para-extender-bootstrap

**Comment by danmarrod** [comment]
Feedback dado: "Hay botones negativos que son más llamativos, lo que incita a darle más a cancelar y borrar que otras acciones en la aplicación"

**Comment by valbarsau** [comment]
Con respecto a los botones lo mejor es ponerlos todos igual que la mayoría. Me asigno la tarea.

**Comment by valbarsau** [comment]
![image](https://cloud.githubusercontent.com/assets/15670602/15116134/61f2f40c-1602-11e6-8ee5-ebcc54ad5262.png)
Asi quedarían

**Comment by moillagar** [comment]
el formulario se queda así? Hay que recordar que donde pone titulo está muy separado

**Comment by valbarsau** [comment]
Esta incidencia es para los botones jeje

**Comment by valbarsau** [comment]
Si nadie mas tiene nada en contra procedo a cambiar los botones de esa manera

**Comment by moillagar** [comment]
asi estan bien

**Comment by danmarrod** [comment]
A nivel de color está bien, pero cuando pasas el ratón por encima como cambia?

**Comment by valbarsau** [comment]
Cambia a un amarillo más fuerte.

**Comment by danmarrod** [comment]
Vale ok, prueba cambiar también el tipo de letra, que sea diferente, el estilo digo. Tamaño y en negrita por ejemplo

**Comment by valbarsau** [comment]
Dime el tipo de letra. Con otro tamaño es peor.

**Comment by danmarrod** [comment]
No sé, prueba en negrita solamente a ver si destaca más

**Comment by valbarsau** [comment]
El aceptar solo? o el cancelar tambien?

**Comment by danmarrod** [comment]
Ambos

**Comment by valbarsau** [comment]
![image](https://cloud.githubusercontent.com/assets/15670602/15117053/1ce9c18e-1606-11e6-8084-0543e5873d22.png)

**Comment by danmarrod** [comment]
Que va la verdad que no me gusta, destaca demasiado sobre la vista...No sé si a lo mejor con mayusculas y la letra más pequeña quedaría mejor, no te quiero marear valentín, ponlo como mejor veas tú.

**Comment by danmarrod** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/15341290/15117298/2dbc4f62-1607-11e6-954b-c32918f92bc0.png)


Así parece que queda bien

**Comment by moillagar** [comment]
La vista de crear un trip no tiene los botones

**Comment by valbarsau** [comment]
Esta incidencia se arregló.
