### ISSUE TITLE
Language se muestra en mayúsculas

### ISSUE THREAD

**Issue by hielfx** [ISPP/pet-care#5]
Language se muestra en mayúsculas. Poner todo en mayúsculas o LANGUAGE en minúscula: [imagen](https://i.gyazo.com/8f6f3cc3eee1d1d3fb28b81ea72d47a0.png)

**Comment by hielfx** [comment]
Users también sale ne mayúsculas: [imagen](https://gyazo.com/69320971144affb2db50135b4a4231d6)

**Comment by viccanjua** [comment]
Solucionada
