### ISSUE TITLE
[IMP] Mejorar visualmente MasterPage

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#50]
Pues eso, mejorarlo visualmente, presentar la misma información mejor formateada, con colores, texto e imagenes menos plano. Puede verse los ejemplos de cualquiera de clase, que presentan mucho menos contenido y con un par de ajustes de formato le quedan muy visual:

http://www.brisbox.com
http://www.te-hace.com

**Comment by danmarrod** [comment]
No digo que tengan que ser igual a la de los ejemplos, sólo que juguemos por ahora con los colores y las letras, que no sea todo negro, minúscula y con el mismo tamaño. Mejorar los botones. Mejorar las imágenes, quizás algunas más grandes tipo iconos y más descriptivas, la del trasporte no queda muy clara a simple vista ni la de los hoteles.

Otra cosa que se me  ha ocurrido es en la búsqueda, se podría poner en vez del selector del tipo de servicio unos iconos con cada servicio y marcarlo directamente.

**Comment by danmarrod** [comment]
Esto añadido a la issue creada aparte del pié de página con botones sociales puede ser más que suficiente.

**Comment by hielfx** [comment]
Referencia las incidencias que tengan relación, así lo tenemos todo más claro y documentado

**Comment by danmarrod** [comment]
Ahí va, https://github.com/ISPP/pet-care/issues/48

**Comment by danmarrod** [comment]
Para mañana con que se arreglen visualmente los botones, y formatee el texto de los registros y demás, es suficiente.

**Comment by hielfx** [comment]
Se ha cambiado el gato en el slider por otra imagen para que el botón de buscar salga en amarillo.

Se ha mejorado la descripción de los usuarios de la siguiente forma:

- Inglés: 
![c303cd8055e17b1ce7b24bd6ef3add21](https://cloud.githubusercontent.com/assets/7794231/15199646/677f863a-17e0-11e6-94c2-d7c779ef9e8c.png)

- Español:
![4e3d4c51c40d2492599e8eeb765da269](https://cloud.githubusercontent.com/assets/7794231/15199675/aa3fcdcc-17e0-11e6-9fb6-ee155f6076d1.png)

**Comment by hielfx** [comment]
Commit referenciado: 164a0c45314367d83ab953cd42e2341348306415
