### ISSUE TITLE
[IMP] Mejorar vista crear Booking/Trip

### ISSUE THREAD

**Issue by moillagar** [ISPP/pet-care#51]
La vista crear booking/trip creo que está demasiado pobre. Con alguna imagen al estilo de la vista de trip creo que puede quedar mas vistosa

**Comment by valbarsau** [comment]
Me la asigno

**Comment by valbarsau** [comment]
¿No tiene sentido modificar la ciudad de destino y de origen, ni la fecha de inicio no?

**Comment by valbarsau** [comment]
Arreglado
