### ISSUE TITLE
Cambiar contraseñas populate

### ISSUE THREAD

**Issue by valbarsau** [ISPP/pet-care#53]
Es necesario cambiar las contraseñas en el populate database.

**Comment by moillagar** [comment]
que contraseñas hay que poner?

**Comment by danmarrod** [comment]
Si os parece ponemos las mismas que el entregable anterior, cambié también los usuarios.

USER	     PASSWORD            DESCRIPTION
admin          6_SeePAmiN_9          Administrator
petowner     6_SeePOwner_9       User owner of pets
petsitter       6_SeePSitter_9         User caring pets
petshipper   6_SeePShipper_9     User transporting pets
company     6_SeePCompany_9   User of pet company

**Comment by danmarrod** [comment]
En slack está el .txt, borrar el comentario cuando lo leais.

**Comment by danmarrod** [comment]
En otra vida quizás, ahora mejor a lo fácil.

**Comment by moillagar** [comment]
realmente hay que poner esas contraseñas? creo que esto no es realmente prioritario pero si no me decis lo contrario le tiro para adelante

**Comment by danmarrod** [comment]
Estaba pensado más que nada por el tema del despliegue, quizás pueda ser un coñazo para las pruebas. Si lo veis mejor si quieres pon otras más asequibles, por mi parte no hay problem.

**Comment by moillagar** [comment]
Cambiadas las contraseñas a lo que el  project manager indicó: 
USER         PASSWORD            DESCRIPTION
admin          6_SeePAmiN_9          Administrator
petowner     6_SeePOwner_9       User owner of pets
petsitter       6_SeePSitter_9         User caring pets
petshipper   6_SeePShipper_9     User transporting pets
company     6_SeePCompany_9   User of pet company
