### ISSUE TITLE
[IMP] Error al buscar company

### ISSUE THREAD

**Issue by moillagar** [ISPP/pet-care#56]
Cuando buscamos company, las estrellas se van al carajo, salen mal posicionadas

**Comment by danmarrod** [comment]
Esto es urgente, por favor que alguien lo solucione cuanto antes para poder mostrar la búsqueda bien con su icono correspondiente.

**Comment by danmarrod** [comment]
Adjuntamos imagen

![pasted_image_at_2016_05_11_01_28_pm](https://cloud.githubusercontent.com/assets/15341290/15179712/d44cfc24-177d-11e6-933b-9a7248e14f78.png)

**Comment by PedroGalvan** [comment]
Solucionado, adjunto captura


![captura](https://cloud.githubusercontent.com/assets/15108206/15192105/156639f2-17b8-11e6-8e07-560bf4d6feca.PNG)

**Comment by moillagar** [comment]
Puedes solucionar de paso el * en el precio? Era otra incidencia

**Comment by PedroGalvan** [comment]
Perdona, eso era con sitter,
Ahora si, con company
![captura](https://cloud.githubusercontent.com/assets/15108206/15192152/43427da4-17b8-11e6-92ce-c3a16bc78e23.PNG)
