### ISSUE TITLE
[IMP]Cambiar formato de las letras

### ISSUE THREAD

**Issue by moillagar** [ISPP/pet-care#57]
Nos dijeron que las letras están muy separadas. Feedback que recibamos y no lo hagamos..ya se sabe lo que es

**Comment by valbarsau** [comment]
Lo he cambiado, mantengo abierta la incidencia por si hay alguna vista que tenga mal las letras.

**Comment by valbarsau** [comment]
Cierro la incidencia puesto que esto ya se arregló.
