### ISSUE TITLE
[IMP] la vista de crear pet/vehicle mejorarla

### ISSUE THREAD

**Issue by moillagar** [ISPP/pet-care#58]
pues eso, solo hayq eu mirar la imagen. Sirva de referencia crear complaint
![image](https://cloud.githubusercontent.com/assets/15704818/15186901/27deff10-179f-11e6-8272-d20e15f5d9ec.png)

**Comment by PedroGalvan** [comment]
Mejorada la vista de crear vehicles
![captura](https://cloud.githubusercontent.com/assets/15108206/15197304/fd23dcc8-17d0-11e6-83ae-9e8786048849.PNG)

**Comment by valbarsau** [comment]
Ya esta terminada la de pet.
