### ISSUE TITLE
Invitaciones independientes del role

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#62]
Poder realizar invitaciones para que otras personas se registren independientemente del rol que tengas, por ejemplo, un PetSitter podrá invitar para que se registren como PetSitter o PetShipper.

**Comment by hielfx** [comment]
Se va a hacer para la presentación final o para esta entrega?

**Comment by danmarrod** [comment]
Para la presentación final si no implica mucho, aun así cuakquier cambio debe resolverse dursnte esta semana para que el próximo finde puedan sacarse las demos

**Comment by valbarsau** [comment]
Me la asigno.

**Comment by valbarsau** [comment]
Terminada.
