### ISSUE TITLE
Formato de los resultados de las búsquedas

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#64]
Mejorar un poco el texto de los perfiles, por ejemplo en la foto que adjunto, en nombre en negrita, el precio más grande u otro color, etc

![panta](https://cloud.githubusercontent.com/assets/15341290/15778771/a72354be-2998-11e6-8551-3ee1ec4da1cb.png)

**Comment by valbarsau** [comment]
¿Cómo debería ser el texto?

**Comment by valbarsau** [comment]
Terminado
