### ISSUE TITLE
Modificación frase de la ventana principal

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#65]
1. Modificar la frase principal que adjunto en la imagen, sólo hace referencia al petsitter. Se podría añadir algo al final sobre el petshipper y la company.

2. Si es posible intentar darle un poco de estilo al texto.

**Comment by danmarrod** [comment]
![sin titulo](https://cloud.githubusercontent.com/assets/15341290/15799783/341413de-2a68-11e6-94f2-879b8b74b3b9.png)

**Comment by valbarsau** [comment]
Un texto como cual?
