### ISSUE TITLE
Modificación imagen predeterminada petshipper

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#66]
Esto es una opinión personal, yo pondría otra más intuitiva para transporte. Es cierto que al ser un pájaro está bien por el tema de la diversidad de las mascotas pero creo que no queda claro. Pondría una como la que paso. Si en general os gusta la que ya está la dejamos.

![file_loader php](https://cloud.githubusercontent.com/assets/15341290/15799855/040d891a-2a6b-11e6-9f42-2136a6aadb4d.jpg)

**Comment by valbarsau** [comment]
Me pongo a ello
