### ISSUE TITLE
Formato en el nombre de los usuarios

### ISSUE THREAD

**Issue by danmarrod** [ISPP/pet-care#67]
Sería sólo ponerlos en mayúsculas y aplicarles el mismo color que el texto de cuando pulsas cada una de las imagenes que tienen justo debajo. Creo que así puede quedar mucho mejor.

![sin titulo](https://cloud.githubusercontent.com/assets/15341290/15799880/f3264aaa-2a6b-11e6-95a0-bf9dcad594c7.png)

![sin titulo](https://cloud.githubusercontent.com/assets/15341290/15799887/5586de62-2a6c-11e6-8b30-347afe426778.png)

**Comment by valbarsau** [comment]
Cambiado.
